{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "de16bde0",
   "metadata": {},
   "source": [
    "### post process the results from the model predictions to see how good they are"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a3e48c45",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import numpy as np\n",
    "from collections import Counter\n",
    "import csv\n",
    "from fractions import Fraction\n",
    "\n",
    "def gcd(a, b):\n",
    "    while b:\n",
    "        a, b = b, a % b\n",
    "    return a\n",
    "\n",
    "def reduce_formula(formula):\n",
    "    counter = Counter(formula)\n",
    "    gcd_value = counter[list(counter.keys())[0]]\n",
    "    for value in counter.values():\n",
    "        gcd_value = gcd(gcd_value, value)\n",
    "    reduced_counter = {key: Fraction(value, gcd_value) for key, value in counter.items()}\n",
    "    return reduced_counter\n",
    "\n",
    "def compare_structures(target, predicted):\n",
    "    # Compare stoichiometry\n",
    "    target_elements = target[\"elements\"]\n",
    "    predicted_elements = predicted[\"elements\"]\n",
    "    target_stoichiometry = reduce_formula(target_elements)\n",
    "    predicted_stoichiometry = reduce_formula(predicted_elements)\n",
    "    stoichiometry_match = target_stoichiometry == predicted_stoichiometry\n",
    "\n",
    "    # Compare lattice constants and angles\n",
    "    target_abc = np.array(target[\"abc\"])\n",
    "    predicted_abc = np.array(predicted[\"abc\"])\n",
    "    target_angles = np.array(target[\"angles\"])\n",
    "    predicted_angles = np.array(predicted[\"angles\"])\n",
    "\n",
    "    lattice_constants_mae = np.abs(target_abc - predicted_abc)\n",
    "    angles_mae = np.abs(target_angles - predicted_angles)\n",
    "\n",
    "    return {\n",
    "        \"stoichiometry_match\": stoichiometry_match,\n",
    "        \"a_mae\": lattice_constants_mae[0],\n",
    "        \"b_mae\": lattice_constants_mae[1],\n",
    "        \"c_mae\": lattice_constants_mae[2],\n",
    "        \"alpha_mae\": angles_mae[0],\n",
    "        \"beta_mae\": angles_mae[1],\n",
    "        \"gamma_mae\": angles_mae[2],\n",
    "    }\n",
    "\n",
    "def process_data(data):\n",
    "    results = []\n",
    "    for item in data:\n",
    "        target = item[\"target\"]\n",
    "        predicted = item[\"predicted\"]\n",
    "        comparison = compare_structures(target, predicted)\n",
    "        results.append({\n",
    "            \"id\": item[\"id\"],\n",
    "            \"stoichiometry_match\": comparison[\"stoichiometry_match\"],\n",
    "            \"a_mae\": comparison[\"a_mae\"],\n",
    "            \"b_mae\": comparison[\"b_mae\"],\n",
    "            \"c_mae\": comparison[\"c_mae\"],\n",
    "            \"alpha_mae\": comparison[\"alpha_mae\"],\n",
    "            \"beta_mae\": comparison[\"beta_mae\"],\n",
    "            \"gamma_mae\": comparison[\"gamma_mae\"],\n",
    "        })\n",
    "    return results\n",
    "\n",
    "def load_json_file(file_path):\n",
    "    try:\n",
    "        with open(file_path, 'r') as f:\n",
    "            data = json.load(f)\n",
    "        return data\n",
    "    except FileNotFoundError:\n",
    "        print(f\"File not found: {file_path}\")\n",
    "        return None\n",
    "    except json.JSONDecodeError as e:\n",
    "        print(f\"Failed to parse JSON: {e}\")\n",
    "        return None\n",
    "\n",
    "def write_to_csv(results, output_file):\n",
    "    fieldnames = [\"id\", \"stoichiometry_match\", \"a_mae\", \"b_mae\", \"c_mae\", \"alpha_mae\", \"beta_mae\", \"gamma_mae\"]\n",
    "    with open(output_file, 'w', newline='') as csvfile:\n",
    "        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)\n",
    "        writer.writeheader()\n",
    "        for result in results:\n",
    "            writer.writerow(result)\n",
    "\n",
    "def main():\n",
    "    file_path = \"test_predictions1.json\"\n",
    "    data = load_json_file(file_path)\n",
    "    if data is not None:\n",
    "        results = process_data(data)\n",
    "        for result in results:\n",
    "            print(f\"ID: {result['id']}\")\n",
    "            print(f\"Stoichiometry match: {result['stoichiometry_match']}\")\n",
    "            print(f\"a MAE: {result['a_mae']}\")\n",
    "            print(f\"b MAE: {result['b_mae']}\")\n",
    "            print(f\"c MAE: {result['c_mae']}\")\n",
    "            print(f\"alpha MAE: {result['alpha_mae']}\")\n",
    "            print(f\"beta MAE: {result['beta_mae']}\")\n",
    "            print(f\"gamma MAE: {result['gamma_mae']}\")\n",
    "            print(\"-\" * 50)\n",
    "        output_file = \"error.csv\"\n",
    "        write_to_csv(results, output_file)\n",
    "        print(f\"Results written to {output_file}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
